# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gen Zu
title: Ph.D. Student in Max Planck Institute for Chemical Physics of Solids
email: gen.zu@cpfs.mpg.de
website: https://genzuuuu.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: sloynica
github_username:  genzuuuu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: zuzuzuzugen
linkedin_username: https://www.linkedin.com/in/gen-zu-494656222/
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: GenZu-m6o
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_photo_with_edge.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Gen and I'm currently a Ph.D. Student in Max Planck Institute for Chemical Physics of Solids in Dresden, Germany. My research interest now focuses on the combination of condensed matter physics and artificial intelligence, especially seeking a new paradigm to describe the quantum many-body physics system.

  I am most skilled in: <mark>Soulslike Gaming</mark> and <mark>Eating KFC</mark>

content:
 # - title: Projects # Title for the section
 #   layout: list # Type of content section (list/text)
 #   content:
 #     - layout: top-middle
 #       title: Super awesome project
 #       link: github.com/sproogen
 #       # link_text: Project Website
 #       additional_links:
 #         - title:  sproogen/modern-resume-theme
 #           icon: fab fa-github
 #           url: github.com/sproogen/modern-resume-theme
 #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
 #         #   icon: fab fa-github
 #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
 #       quote: >
 #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
 #       description: | # this will include new lines to allow paragraphs
 #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Max Planck Institute of Microstructure Physics
        link: https://www.mpi-halle.mpg.de/startseite
        link_text: mpi-halle.mpg.de
        sub_title: Research Assistant
        caption: May 2023 - November 2024
        quote: >
          Optical Computing and automated photonics design
        description: | # this will include new lines to allow paragraphs
            As we know, the field of artificial intelligence (AI) is rapidly advancing, with recent examples such as Sora for video generation or ChatGPT for natural language inter- action that can enhance human productivity. So, our goal is to explore how machine learning models, particularly large language models, which is usually called LLM, can assist in designing photonic integrated circuits and help to accelerate the photonics research.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Imperial College London
        caption: 2021 - 2022
        sub_title: MSc Optics and Photonics
        quote: >
          Imperial College London is a world-leading university for science, technology, engineering, medicine and business (STEMB).
        description: | # this will include new lines to allow paragraphs
          During my time at Imperial College London. I learned most of my optical experimental skills, especially surface-enhanced Raman scattering technique. And I finshied several plasmonics and nanophotonics courses as well. My supervisor is Prof. Rupert Oulton.

      - layout: left
        title: University of Electronic Science and Technology of China
        caption: 2017 - 2021
        sub_title: BEng Opto-electronic Information Science and Engineering
        quote: >
          UESTC is a multidisciplinary research university with electronic science and technology as its nucleus, engineering as its major field, and featured with management, liberal art and medicine.
        description: | # this will include new lines to allow paragraphs
         During the years at UESTC, I completed various optoelectronics-related core courses and developed an engineering mindset. This played a big role in my later research and work. As the motto of UESTC says: To seek facts and truth, to be noble and ambitious.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in physics and machine learning some of my other interests and hobbies are:
      - Snowboarding
      - Gaming
      - Cooking
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
